표준 예외 처리 클래스 : RuntimeException, IllegalArgumentException, IllegalStateException, NoSuchElementException

함수에서 throw로 예외를 던질 수 있음
함수를 호출하는 쪽에서 예외를 catch하여 처리 가능

try, catch, finally 구문 이용

Exception은 처리하고 Error는 심각한 오류이므로 처리 없이 Error를 내는 것이 권장됨.

- - -
[토스 테크](https://toss.tech/article/kotlin-result)
runCatching과 Result 활용하기
```kotlin
@InlineOnly  
@SinceKotlin("1.3")  
public inline fun <R> runCatching(block: () -> R): Result<R> {  
    return try {  
        Result.success(block())  
    } catch (e: Throwable) {  
        Result.failure(e)  
    }  
}
```
내부에 try-catch 구문을 사용한다.
단지 Result(.success, .failure)로 값을 반환하는데 Result<\T>와 Result<Failure<\exception>> 값.
